V 1.1/ProyectoFinal/ProyectoFinal/Controllers/DptoOCabanaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;

namespace ProyectoFinal.Controllers
{
    public class DptoOCabanaController : Controller
    {
        private SitcomEntities db = new SitcomEntities();

        // GET: /CasaODpto/
        public ActionResult Index(int idComplejo)
        {
            var casadptoocabana = db.CasaDptoOCabana
                                           .Include(c => c.Complejo)
                                           .Include(c => c.LugarHospedaje)
                                           .Where(c => c.idComplejo == idComplejo);

            return View(casadptoocabana.ToList());
        }
        // GET: /CasaODpto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CasaDptoOCabana casadptoocabana = db.CasaDptoOCabana.Find(id);
            if (casadptoocabana == null)
            {
                return HttpNotFound();
            }
            return View(casadptoocabana);
        }
        // GET: /CasaODpto/Create
        public ActionResult Create(int idComplejo)
        {
            ViewBag.idComplejo = idComplejo;
            ViewBag.idLugarHospedaje = new SelectList(db.LugarHospedaje, "idLugarHospedaje", "idLugarHospedaje");
            return View();
        }
        // POST: /CasaODpto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="idCasaDptoOCabana,nombreCasaDptoOCabana,idLugarHospedaje,cantidadHabitaciones,cantidadAmbientes,cantidadBanios,idComplejo,capacidadMaxima")] CasaDptoOCabana casadptoocabana)
        {
            if (ModelState.IsValid)
            {
                db.CasaDptoOCabana.Add(casadptoocabana);
                db.SaveChanges();
                return RedirectToAction("Index", new { idComplejo = casadptoocabana.idComplejo });
            }

            ViewBag.idComplejo = new SelectList(db.Complejo, "idComplejo", "idComplejo", casadptoocabana.idComplejo);
            ViewBag.idLugarHospedaje = new SelectList(db.LugarHospedaje, "idLugarHospedaje", "idLugarHospedaje", casadptoocabana.idLugarHospedaje);
            return View(casadptoocabana);
        }
        // GET: /CasaODpto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CasaDptoOCabana casadptoocabana = db.CasaDptoOCabana.Find(id);
            if (casadptoocabana == null)
            {
                return HttpNotFound();
            }
            ViewBag.idComplejo = new SelectList(db.Complejo, "idComplejo", "idComplejo", casadptoocabana.idComplejo);
            ViewBag.idLugarHospedaje = new SelectList(db.LugarHospedaje, "idLugarHospedaje", "idLugarHospedaje", casadptoocabana.idLugarHospedaje);
            return View(casadptoocabana);
        }
        // POST: /CasaODpto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="idCasaDptoOCabana,nombreCasaDptoOCabana,idLugarHospedaje,cantidadHabitaciones,cantidadAmbientes,cantidadBanios,idComplejo,capacidadMaxima")] CasaDptoOCabana casadptoocabana)
        {
            if (ModelState.IsValid)
            {
                db.Entry(casadptoocabana).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { idComplejo = casadptoocabana.idComplejo });
            }
            ViewBag.idComplejo = new SelectList(db.Complejo, "idComplejo", "idComplejo", casadptoocabana.idComplejo);
            ViewBag.idLugarHospedaje = new SelectList(db.LugarHospedaje, "idLugarHospedaje", "idLugarHospedaje", casadptoocabana.idLugarHospedaje);
            return View(casadptoocabana);
        }
        // GET: /CasaODpto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CasaDptoOCabana casadptoocabana = db.CasaDptoOCabana.Find(id);
            if (casadptoocabana == null)
            {
                return HttpNotFound();
            }
            return View(casadptoocabana);
        }
        // POST: /CasaODpto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CasaDptoOCabana casadptoocabana = db.CasaDptoOCabana.Find(id);
            int idComplejo = (int)casadptoocabana.idComplejo;
            db.CasaDptoOCabana.Remove(casadptoocabana);
            db.SaveChanges();
            return RedirectToAction("Index", new { idComplejo = idComplejo });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

V 1.1/ProyectoFinal/ProyectoFinal/Controllers/HabitacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;

namespace ProyectoFinal.Controllers
{
    public class HabitacionesController : Controller
    {
        private SitcomEntities db = new SitcomEntities();

        // GET: /Habitaciones/
        public ActionResult Index(int idHotel)
        {
            var habitacion = db.Habitacion.Include(h => h.Hotel)
                                          .Include(h => h.TipoHabitacion)
                                          .Where(h => h.idHotel == idHotel);

            return View(habitacion.ToList());
        }

        // GET: /Habitaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitacion habitacion = db.Habitacion.Include(h => h.Hotel)
                                          .Include(h => h.TipoHabitacion)
                                          .Where(h => h.idHabitacion == id).FirstOrDefault();
            if (habitacion == null)
            {
                return HttpNotFound();
            }
            return View(habitacion);
        }

        // GET: /Habitaciones/Create
        public ActionResult Create(int? idHotel)
        {
            if (idHotel != null)
                ViewBag.idHotel = idHotel;
            ViewBag.idTipoHabitacion = new SelectList(db.TipoHabitacion, "idTipoHabitacion", "nombre");
            return View();
        }

        // POST: /Habitaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="idHabitacion,idTipoHabitacion,cantidadBanios,balcon,heladera,microondas,idHotel,nombreHabitacion")] Habitacion habitacion)
        {
            if (ModelState.IsValid)
            {
                db.Habitacion.Add(habitacion);
                db.SaveChanges();
                return RedirectToAction("Index", new { idHotel = habitacion.idHotel });
            }

            ViewBag.idHotel = habitacion.idHotel;
            ViewBag.idTipoHabitacion = new SelectList(db.TipoHabitacion, "idTipoHabitacion", "nombre", habitacion.idTipoHabitacion);
            return View(habitacion);
        }

        // GET: /Habitaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitacion habitacion = db.Habitacion.Find(id);
            if (habitacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.idTipoHabitacion = new SelectList(db.TipoHabitacion, "idTipoHabitacion", "nombre", habitacion.idTipoHabitacion);
            return View(habitacion);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="idHabitacion,idTipoHabitacion,cantidadBanios,balcon,heladera,microondas,nombreHabitacion,idHotel")] Habitacion habitacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(habitacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { idHotel = habitacion.idHotel });
            }
            ViewBag.idTipoHabitacion = new SelectList(db.TipoHabitacion, "idTipoHabitacion", "nombre", habitacion.idTipoHabitacion);
            return View(habitacion);
        }

        // GET: /Habitaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitacion habitacion = db.Habitacion.Include("TipoHabitacion").Where(h => h.idTipoHabitacion == id).FirstOrDefault();
            if (habitacion == null)
            {
                return HttpNotFound();
            }
            return View(habitacion);
        }

        // POST: /Habitaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Habitacion habitacion = db.Habitacion.Find(id);
            db.Habitacion.Remove(habitacion);
            db.SaveChanges();
            return RedirectToAction("Index", new { idHotel = habitacion.idHotel });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

V 1.1/ProyectoFinal/ProyectoFinal/Views/DptoOCabana/Index.cshtml
@model IEnumerable<DAL.CasaDptoOCabana>

@{
    ViewBag.Title = "Index";
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Tus Departamentos</title>
    <!-- start: META -->
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/assets/plugins/animate.css/animate.min.css">
    <!-- end: MAIN CSS -->
    <!-- start: CSS REQUIRED FOR SUBVIEW CONTENTS -->
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="~/assets/plugins/summernote/dist/summernote.css">
    <link rel="stylesheet" href="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="~/assets/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-select/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
    <link rel="stylesheet" href="~/assets/plugins/DataTables/media/css/DT_bootstrap.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
    <!-- end: CSS REQUIRED FOR THIS SUBVIEW CONTENTS-->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link rel="stylesheet" href="~/assets/plugins/weather-icons/css/weather-icons.min.css">
    <link rel="stylesheet" href="~/assets/plugins/nvd3/nv.d3.min.css">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CORE CSS -->
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="stylesheet" href="~/assets/css/styles-responsive.css">
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <link rel="stylesheet" href="~/assets/css/themes/theme-default.css" type="text/css" id="skin_color">
    <link rel="stylesheet" href="~/assets/css/print.css" type="text/css" media="print" />
    <!-- end: CORE CSS -->
</head>
<body>
    <div class="panel panel-white" style="width:1190px;">
        <div class="panel-heading">
            <h2 class="panel-title"><span class="text-bold">Departamentos</span></h2>
        </div>
        <div class="panel-body">
          

           

            @*<a href='@Url.Action("Edit", "Habitaciones", new { idComplejo = Model.FirstOrDefault().idComplejo })' class="btn btn-blue" ><i class="fa fa-plus"></i>Agregar Depto/Cabaña</a>*@
            <br />

              
              @Html.ActionLink("NUEVO DEPARTAMENTO/CABAÑA", "Create", new { idComplejo = Model.FirstOrDefault().idComplejo, @class = "btn btn-blue pull-right" })          
          
            
            
              <table class="table">
                <tr>
                    <th>
                        @Html.Label("Departamento/Cabaña")
                    </th>
                    <th>
                        @Html.Label("Capacidad Máxima")
                    </th>
                    <th class="text-bold">
                        
                        <span class="text-bold">@Html.Label("Opciones")</span>
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombreCasaDptoOCabana)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.capacidadMaxima)
                        </td>
                        <td>
                            <div class="visible-md visible-lg hidden-sm hidden-xs">
                                <a href='@Url.Action("Edit", "DptoOCabana", new { id = item.idCasaDptoOCabana })' class="btn btn-xs btn-blue tooltips" data-placement="top" data-original-title="Editar"><i class="fa fa-edit"></i></a>
                                <a href='@Url.Action("Details", "DptoOCabana", new { id = item.idCasaDptoOCabana })' class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="Ver"><i class="fa fa-search"></i></a>
                                <a href='@Url.Action("Delete", "DptoOCabana", new { id = item.idCasaDptoOCabana })' class="btn btn-xs btn-red tooltips" data-placement="top" data-original-title="Eliminar"><i class="fa fa-times fa fa-white"></i></a>
                                @*@Html.ActionLink("MODIFICAR", "Edit", new { id = item.idCasaDptoOCabana }) |
                                @Html.ActionLink("DETALLES", "Details", new { id = item.idCasaDptoOCabana }) |
                                @Html.ActionLink("ELIMINAR", "Delete", new { id = item.idCasaDptoOCabana })*@
                              </div>
                            <div class="visible-xs visible-sm hidden-md hidden-lg">
                                <div class="btn-group">
                                    <a class="btn btn-green dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
                                        <i class="fa fa-cog"></i> <span class="caret"></span>
                                    </a>
                                    <ul role="menu" class="dropdown-menu pull-right dropdown-dark">
                                        <li>
                                            <a role="menuitem" tabindex="-1" href="#">
                                                <i class="fa fa-edit"></i> Editar
                                            </a>
                                        </li>
                                        <li>
                                            <a role="menuitem" tabindex="-1" href="#">
                                                <i class="fa fa-share"></i> Ver
                                            </a>
                                        </li>
                                        <li>
                                            <a role="menuitem" tabindex="-1" href="#">
                                                <i class="fa fa-times"></i> Eliminar
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
</td>
                    </tr>
                }

            </table>

        </div>
    </div>

            <script src="~/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
            <!--<![endif]-->
            <script src="~/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
            <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
            <script src="~/assets/plugins/blockUI/jquery.blockUI.js"></script>
            <script src="~/assets/plugins/iCheck/jquery.icheck.min.js"></script>
            <script src="~/assets/plugins/moment/min/moment.min.js"></script>
            <script src="~/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
            <script src="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
            <script src="~/assets/plugins/bootbox/bootbox.min.js"></script>
            <script src="~/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
            <script src="~/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
            <script src="~/assets/plugins/jquery.appear/jquery.appear.js"></script>
            <script src="~/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
            <script src="~/assets/plugins/velocity/jquery.velocity.min.js"></script>
            <script src="~/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
            <!-- end: MAIN JAVASCRIPTS -->
            <!-- start: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
            <script src="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
            <script src="~/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
            <script src="~/assets/plugins/toastr/toastr.js"></script>
            <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
            <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
            <script src="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
            <script src="~/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
            <script src="~/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
            <script src="~/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
            <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
            <script src="~/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
            <script src="~/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
            <script src="~/assets/plugins/truncate/jquery.truncate.js"></script>
            <script src="~/assets/plugins/summernote/dist/summernote.min.js"></script>
            <script src="~/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
            <script src="~/assets/js/subview.js"></script>
            <script src="~/assets/js/subview-examples.js"></script>
            <!-- end: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
            <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
            <script src="~/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
            <script src="~/assets/plugins/autosize/jquery.autosize.min.js"></script>
            <script src="~/assets/plugins/select2/select2.min.js"></script>
            <script src="~/assets/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
            <script src="~/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
            <script src="~/assets/plugins/jquery-maskmoney/jquery.maskMoney.js"></script>
            <script src="~/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
            <script src="~/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpicker/js/commits.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js"></script>
            <script src="~/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
            <script src="~/assets/plugins/jQuery-Tags-Input/jquery.tagsinput.js"></script>
            <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
            <script src="~/assets/plugins/ckeditor/ckeditor.js"></script>
            <script src="~/assets/plugins/ckeditor/adapters/jquery.js"></script>
            <script src="~/assets/js/form-elements.js"></script>
            <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
            <!-- start: CORE JAVASCRIPTS  -->
            <script src="~/assets/js/main.js"></script>
            <!-- end: CORE JAVASCRIPTS  -->
            <script>
                jQuery(document).ready(function () {
                    Main.init();

                    FormElements.init();
                    SVExamples.init();
                });
            </script>

</body>
</html>