V 1.1/ProyectoFinal/ProyectoFinal/Controllers/TramitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using BussinesEntities;
using DAL;

namespace ProyectoFinal.Controllers
{
    public class TramitesController : Controller
    {
        //
        // GET: /Tramites/
        private UsuarioEntity usuarioActual;
        private UsuariosManager um = new UsuariosManager();
        private TramitesManager tm = new TramitesManager();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TramitesResp(int? id)
        {
            List<TramiteEntity> tramites = tm.GetAllTramites(id);

            foreach (var item in tramites)
            {
                if (item.idUsuarioResponsable == null)
                    item.Usuarios1 = new Usuarios() { nombreUsuario = "No Asignado" };
            }
            return View(tramites);
        }
        public ActionResult TomarTramiteResp(int id)
        {
            ObtenerUsuarioActual();
            TramiteEntity tra = tm.GetTramiteById(id);
            tm.CambiarEstadoTramite(tra, 2, usuarioActual);

            return RedirectToAction("TramitesResp");
        }
        public ActionResult CancelarTramite(int id, string returnUrl)
        {
            ObtenerUsuarioActual();
            TramiteEntity tra = tm.GetTramiteById(id);
            tm.CambiarEstadoTramite(tra, 5, usuarioActual);
            return RedirectToAction(returnUrl, new { mensaje = "¡Tu tramite fue cancelado!" });
        }
        public ActionResult TramitesUsuario(string mensaje)
        {
            ObtenerUsuarioActual();

            ViewBag.Perfil = usuarioActual.idPerfil;
            ViewBag.UsuarioActual = usuarioActual;
            ViewBag.Mensaje = mensaje;
            List<TramiteEntity> tramites = tm.GetTramitesByUsuario(usuarioActual);

            return View(tramites);
        }
        public ActionResult VerTramite(int id)
        {
            TramiteEntity tra = tm.GetTramiteById(id);

            switch (tra.idTipoTramite)
            {
                case 1: return RedirectToAction("EvalNegocio", "Negocios", new { id = tra.idNegocio, idTramite = tra.idTramite});
                case 2: return RedirectToAction("EvalSolicitudModulo", "Reservas", new { id = tra.idNegocio, idTramite = tra.idTramite });
                case 3: return RedirectToAction("EvalNegocio", "Negocios", new { id = tra.idNegocio, idTramite = tra.idTramite });
                default: return RedirectToAction("Index","Home");
           
            }
        }
        public ActionResult ResolverTramite(int idtramite, int accion, string comentario)
        {
            ObtenerUsuarioActual();
            TramiteEntity tra = tm.GetTramiteById(idtramite);
            tm.CambiarEstadoTramite(tra, accion, usuarioActual);

            return RedirectToAction("PanelControlUsuario", "Usuarios", new { mensaje = "Se resolvio el tramite correctamente!" });
        }
        public bool ValidarPermisoVista(string controlador, string vista) //METODO UNICO DEL CONTROLADOR PARA VALIDAR PERMISO DE LA VISTA (LLAMA AL MANEJADOR).
        {
            ObtenerUsuarioActual();
            return um.ValidarPermisoVista(usuarioActual, controlador, vista);
        }
        public void ObtenerUsuarioActual()
        {
            usuarioActual = (UsuarioEntity)Session["User"];
        }
	}
}

V 1.1/ProyectoFinal/ProyectoFinal/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;
using BL;
using BussinesEntities;
using System.Web.Security;

namespace ProyectoFinal
{
    public class UsuariosController : Controller
    {
        private UsuarioEntity usuarioActual;
        private SitcomEntities db = new SitcomEntities();
        private UsuariosManager um = new UsuariosManager();
     
        public ActionResult Index()
        {
          if (ValidarPermisoVista("Usuarios", "Index"))
            {
                var usuarios = um.GetAllUsuarios();
                return View(usuarios);
            }
            else
            {
                return RedirectToAction("ErrorPermisos","Errores");
            }
        } //PANTALLA PRINCIPAL - USUARIOS
        public ActionResult Details(int? id)
        {
            if (ValidarPermisoVista("Usuarios", "Details"))
            {
                UsuarioEntity us = um.GetUsuarioById(id);
                return View(us);
            }
            else
            {
                ModelState.AddModelError("", "No podés acceder a esta página. Tu usuario NO tiene permisos");
                return RedirectToAction("Index", "Home");
            }
            
        } //PANTALLA DETALLES - USUARIOS
        public ActionResult Nuevo() //PANTALLA CREAR NUEVO - USUARIOS
        {
            ObtenerUsuarioActual();
            ViewBag.Perfil = usuarioActual.idPerfil;
            ViewBag.Perfiles = new SelectList(db.Perfiles, "idPerfil", "nombre");
            return View();
        }
        [HttpPost] //SE INDICA QUE EL METODO SE INVOCA A PARTIR DE UNA LLAMADA POST.
        [ValidateAntiForgeryToken]
        // SOBRECARGA QUE ENVÍA EL USUARIO A CREAR.
        public ActionResult Nuevo([Bind(Include="idUsuario,nombreUsuario,password,confirmarPassword,idPerfil")] UsuarioEntity usuario)
        {
            ObtenerUsuarioActual();

            if (usuario.idPerfil == null)
                usuario.idPerfil = 1;

            if (ModelState.IsValid)
            {
                if(um.GetUsuarioByNombre(usuario.nombreUsuario) == null)
                    um.AddUsuarios(usuario);
                else
                {
                    ModelState.AddModelError("", "El usuario ingresado ya está registrado. Por favor verifícalo.");
                    ViewBag.Perfil = usuarioActual.idPerfil;
                    ViewBag.Perfiles = new SelectList(db.Perfiles, "idPerfil", "nombre");
                    return View("Nuevo", usuario);
                }
            }

            return RedirectToAction("Index","Home");
        }
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (ValidarPermisoVista("Usuarios", "Edit"))
            {
                ObtenerUsuarioActual();

                bool esMismoUsuario = false;

                if (usuarioActual.idUsuario == id)
                    esMismoUsuario = true;

                UsuarioEntity us = um.GetUsuarioById(id);
                ViewBag.MismoUsuario = esMismoUsuario;
                ViewBag.Perfiles = new SelectList(db.Perfiles, "idPerfil", "nombre", us.idPerfil);
                ViewBag.Perfil = usuarioActual.idPerfil;
                ViewBag.ReturnUrl = returnUrl;
                return View(us);                      
            }
            else
                return RedirectToAction("ErrorPermisos", "Errores");
         } //PANTALLA EDITAR - USUARIOS
        [HttpPost]  //SE INDICA QUE EL METODO SE INVOCA A PARTIR DE UNA LLAMADA POST.
        [ValidateAntiForgeryToken]
        // SOBRECARGA QUE ENVÍA EL USUARIO A EDITAR.
        public ActionResult Edit([Bind(Include="idUsuario,nombreUsuario,password,confirmarPassword,idPerfil")] UsuarioEntity usuarios, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                um.UpdateUsuarios(usuarios);
                return RedirectToAction(returnUrl);
            }
            ViewBag.idPerfil = new SelectList(db.Perfiles, "idPerfil", "nombre", usuarios.idPerfil);
            return View(usuarios);
        }
        public ActionResult EditUsuario()
        {
            ObtenerUsuarioActual();

            ViewBag.Perfil = usuarioActual.idPerfil;
            ViewBag.Perfiles = new SelectList(db.Perfiles, "idPerfil", "nombre",usuarioActual.idPerfil);

            return View(usuarioActual);
        }
        public ActionResult Delete(int? id)
        {
            if (ValidarPermisoVista("Usuarios", "Delete"))
            {
                UsuarioEntity us = um.GetUsuarioById(id);
                return View(us);
            }
            else
                return RedirectToAction("ErrorPermisos", "Errores");

        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        // SOBRECARGA QUE ENVÍA EL USUARIO A EDITAR.
        public ActionResult DeleteConfirmed(int id)
        {
            um.DeleteUsuarios(id);
            return RedirectToAction("Index");
        }
        public ActionResult Login()
        {
            ObtenerUsuarioActual();

            if (usuarioActual.idUsuario == 0)
                return View();
            else
                return RedirectToAction("ErrorPermisos", "Errores");
        } //PANTALLA DE LOGIN DE USUARIOS
        public ActionResult LoginUser([Bind(Include="nombreUsuario,password")] UsuarioEntity us)
        {
            if(um.ValidarUsuario(us.nombreUsuario, us.password) != null)
            {
                us = um.ValidarUsuario(us.nombreUsuario, us.password);
                Session["User"] = us;
                FormsAuthentication.SetAuthCookie(us.nombreUsuario, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "El usuario o contraseña ingresados no son correctos.");
                return View("Login", us);
            }
        } //VALIDACIÓN Y LOGGEO DE USUARIO EN EL SISTEMA.
        public ActionResult LogOff()
        {
            FormsAuthentication.SetAuthCookie(null, false);
            Session["User"] = new UsuarioEntity();
            return RedirectToAction("Index", "Home");
        } //DESLOGGEO DEL USUARIO DEL SISTEMA.
        public ActionResult PanelControlUsuario(string mensaje)
        {
            if (mensaje == null)
                mensaje = "";

            ObtenerUsuarioActual();
            ViewBag.Perfiles = new SelectList(db.Perfiles, "idPerfil", "nombre", usuarioActual.idPerfil);
            ViewBag.Perfil = usuarioActual.idPerfil;
            ViewBag.Mensaje = mensaje;
            return View(usuarioActual);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public bool ValidarPermisoVista(string controlador,string vista) //METODO UNICO DEL CONTROLADOR PARA VALIDAR PERMISO DE LA VISTA (LLAMA AL MANEJADOR).
        {
           ObtenerUsuarioActual();
           return um.ValidarPermisoVista(usuarioActual, controlador, vista);
        }
        public void ObtenerUsuarioActual()
        {
            usuarioActual = (UsuarioEntity)Session["User"];
        }
    }
}

V 1.1/ProyectoFinal/ProyectoFinal/Views/Usuarios/Login.cshtml
@model BussinesEntities.UsuarioEntity
@{
    ViewBag.Title = "";
}

<html lang="en" class="no-js">
<head>
    <title></title>
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/plugins/animate.css/animate.min.css">
    <link rel="stylesheet" href="~/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="stylesheet" href="~/assets/css/styles-responsive.css">
    <link rel="stylesheet" href="~/assets/plugins/iCheck/skins/all.css">
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body class="login">
    <div class="row">
        <div class="main-login col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
            <div class="box-login">
                <h2>Inicie Sesión</h2>
               
                    <fieldset>

                        @ViewBag.Error

                        @using (Html.BeginForm("LoginUser", "Usuarios", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-login"}))
                        {
                            @Html.AntiForgeryToken()
                            <hr />
                            @Html.ValidationSummary(true)
                            <div class="form-group">
                                @*@Html.Label("Usuario (Mail)", new { @class = "col-md-2 control-label" })*@
                                <span class="input-icon">
                                    @Html.TextBoxFor(m => Model.nombreUsuario, new { @class = "form-control", name = "username", placeholder = "Username" })
                                    @Html.ValidationMessageFor(m => Model.nombreUsuario)
                                    <i class="fa fa-user"></i>
                                </span>
                            </div>
    <div class="form-group form-actions">
        @*@Html.Label("Password", new { @class = "col-md-2 control-label" })*@
        <span class="input-icon">
            @Html.PasswordFor(m => Model.password, new { @class="form-control", name="password", placeholder="Password" })
            @Html.ValidationMessageFor(m => Model.password)
            <i class="fa fa-lock"></i>
          
        </span>
    </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    @ViewBag.Error
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3 col-md-10">
                                    <button type="submit"  class="btn btn-green pull-left">
                                     Ingresar <i class="fa fa-arrow-circle-right"></i>
                                        </button>
                                    
                                </div>
                                <br />
                                <br />
                            </div>
                            
                            <p>
                                
                                @Html.ActionLink("Registrate!", "Nuevo", "Usuarios")
                                @Html.ActionLink("¿Olvidaste tu contraseña?", "Login", "Usuarios")
                            </p>
                        }





                    </fieldset>
               
                   

                
              
                 
                
                     
</div>
           
        </div>
     
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    <script src="~/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
        <!--<![endif]-->
        <script src="~/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
        <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/assets/plugins/iCheck/jquery.icheck.min.js"></script>
        <script src="~/assets/plugins/jquery.transit/jquery.transit.js"></script>
        <script src="~/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
        <script src="~/assets/js/main.js"></script>
        <!-- end: MAIN JAVASCRIPTS -->
        <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
        <script src="~/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/assets/js/login.js"></script>
        <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
        <script>
            jQuery(document).ready(function () {
                Main.init();
                Login.init();
            });
        </script>
    }


</body>
</html>

V 1.1/ProyectoFinal/ProyectoFinal/Views/Usuarios/PanelControlUsuario.cshtml
@{
    ViewBag.Title = "Panel de Control";
}
@model BussinesEntities.UsuarioEntity

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Panel de Usuario</title>
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/assets/plugins/animate.css/animate.min.css">
    <!-- end: MAIN CSS -->
    <!-- start: CSS REQUIRED FOR SUBVIEW CONTENTS -->
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="~/assets/plugins/summernote/dist/summernote.css">
    <link rel="stylesheet" href="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="~/assets/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-select/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
    <link rel="stylesheet" href="~/assets/plugins/DataTables/media/css/DT_bootstrap.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
    <!-- end: CSS REQUIRED FOR THIS SUBVIEW CONTENTS-->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-social-buttons/bootstrap-social.css">
    <link rel="stylesheet" href="~/assets/plugins/ladda-bootstrap/dist/ladda.min.css">
    <link rel="stylesheet" href="~/assets/plugins/ladda-bootstrap/dist/ladda-themeless.min.css">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CORE CSS -->
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="stylesheet" href="~/assets/css/styles-responsive.css">
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <link rel="stylesheet" href="~/assets/css/themes/theme-default.css" type="text/css" id="skin_color">
    <link rel="stylesheet" href="~/assets/css/print.css" type="text/css" media="print" />
    <!-- end: CORE CSS -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.custom.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>

    <script type="text/javascript">

        var perfil = "@Model.idPerfil"
        var mensaje = "@ViewBag.Mensaje"

        $(document).ready(function () {

            if (perfil == 3) {
                $("#btnTusTramites").hide();
                $("#btnTusNegocios").hide();
                $("#btnTusTramitesAsignados").show();
                $("#tabSecretaria").show();
            }
            else {
                $("#btnTusTramites").show();
                $("#btnTusNegocios").show();
                $("#btnTusTramitesAsignados").hide();
            }

            if (mensaje != "") {
                alert(mensaje);
            }

            $("#btnTusTramites").click(function () {
                window.location = '@Url.Action("TramitesUsuario","Tramites")';
            });

            $("#btnTusTramitesAsignados").click(function () {
                window.location = '@Url.Action("TramitesUsuario","Tramites")';
            });

            $("#btnModificarDatos").click(function () {
                window.location = '@Url.Action("EditUsuario","Usuarios")';                
            });

            $("#btnTusNegocios").click(function () {
                window.location = '@Url.Action("NegociosUsuario","Negocios")';
            });
        });

    </script>

</head>
<body>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-white" style="width:1190px;">
                <div class="panel-heading">
                    <h4 class="panel-title">Usuario: <span class="text-bold">@Model.nombreUsuario</span></h4>
                    <h4>@Html.DisplayFor(model => model.Perfiles.nombre)</h4>
                </div>
                
                           
                   
                <table cellspacing="3" cellpadding="3" class="tabla-principal" align="center">

                    <tr>
                        <td>
                            <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnModificarDatos">
                                MODIFICÁ TUS DATOS
                            </button>
                            <br />
                           
                        </td>
                        <td>
                            <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnTusNegocios">
                                TUS NEGOCIOS
                            </button>
                            <br />
                            
                        </td>
                        <td>
                            <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnTusTramites">
                                TUS TRAMITES
                            </button>
                            <br />
                           
                        </td>
                        <td>
                            <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnTusTramitesAsignados">
                                TUS TRAMITES ASIGNADOS
                            </button>
                        </td>
                    </tr>
                </table>

                <br />
                <br />
                <div class="col-lg-offset-10">
                    @Html.ActionLink("VER TODOS LOS TRAMITES", "../Tramites/TramitesResp")
                </div>
                <div id="mostrar" style="align-self:center;">
                    @*@Html.Partial(Url.Action("TramitesUsuario","Tramites", Model.idUsuario))*@
                    @*@Html.Partial("~/Views/Tramites/TramitesUsuario.cshtml", (new BL.TramitesManager()).GetTramitesByUsuario(Model), new ViewDataDictionary { { "Perfil",Model.idPerfil }})*@
                </div>
            </div>
        </div>
    </div>

    <script src="~/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
    <!--<![endif]-->
    <script src="~/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/plugins/blockUI/jquery.blockUI.js"></script>
    <script src="~/assets/plugins/iCheck/jquery.icheck.min.js"></script>
    <script src="~/assets/plugins/moment/min/moment.min.js"></script>
    <script src="~/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
    <script src="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
    <script src="~/assets/plugins/bootbox/bootbox.min.js"></script>
    <script src="~/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
    <script src="~/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
    <script src="~/assets/plugins/jquery.appear/jquery.appear.js"></script>
    <script src="~/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
    <script src="~/assets/plugins/velocity/jquery.velocity.min.js"></script>
    <script src="~/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
    <!-- end: MAIN JAVASCRIPTS -->
    <!-- start: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
    <script src="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
    <script src="~/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
    <script src="~/assets/plugins/toastr/toastr.js"></script>
    <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
    <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
    <script src="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
    <script src="~/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
    <script src="~/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
    <script src="~/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
    <script src="~/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
    <script src="~/assets/plugins/truncate/jquery.truncate.js"></script>
    <script src="~/assets/plugins/summernote/dist/summernote.min.js"></script>
    <script src="~/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script src="~/assets/js/subview.js"></script>
    <script src="~/assets/js/subview-examples.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="~/assets/plugins/ladda-bootstrap/dist/spin.min.js"></script>
    <script src="~/assets/plugins/ladda-bootstrap/dist/ladda.min.js"></script>
    <script src="~/assets/js/ui-buttons.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CORE JAVASCRIPTS  -->
    <script src="~/assets/js/main.js"></script>
    <!-- end: CORE JAVASCRIPTS  -->
    <script>
        jQuery(document).ready(function () {
            Main.init();
            SVExamples.init();
            UIButtons.init();
        });
    </script>



          

</body>
</html>