V 1.1/ProyectoFinal/ProyectoFinal/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using DAL;
using BussinesEntities;

namespace ProyectoFinal.Controllers
{
    public class ReservasController : Controller
    {
        UsuarioEntity usuarioActual;
        SitcomEntities db = new SitcomEntities();
        NegociosManager nm = new NegociosManager();
        UsuariosManager um = new UsuariosManager();
        PersonasManager pm = new PersonasManager();
        ReservasManager rm = new ReservasManager();

        // GET: /Reservas/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SolicitarModulo(int? idNegocio)
        {
            ObtenerUsuarioActual();
            NegocioEntity neg = nm.GetNegocioById((int)idNegocio);
            Persona p = pm.GetPersonaById((int)usuarioActual.idPersona);

            ViewBag.Persona = p;

            return View(neg);
        }
        [HttpPost]
        public ActionResult SolicitarModulo(bool aceptaCondiciones, int idNegocio)
        {
            ObtenerUsuarioActual();
            if(aceptaCondiciones == true)
            {
                rm.SolicitarModuloReservas(idNegocio, usuarioActual);
                return RedirectToAction("Index","Home");
            }
            else
            {                
                NegocioEntity neg = nm.GetNegocioById(idNegocio);

                Persona p = pm.GetPersonaById(usuarioActual.idUsuario);
                ViewBag.Persona = p;

                ViewBag.Error = 1;
                return View("SolicitarModulo",neg);
            }
        }
        public ActionResult EvalSolicitudModulo(int id, int idTramite)
        {
            NegocioEntity neg = nm.GetNegocioById(id);
            Persona p = pm.GetPersonaById((int)neg.Usuarios.idPersona);

            ViewBag.Persona = p;
            ViewBag.Tramite = idTramite;

            return View(neg);
        }
        public ActionResult GestionReservas(int idNegocio)
        {
            NegocioEntity neg = nm.GetNegocioById(idNegocio);

            return View(neg);
        }
        public ActionResult SolicitarReserva(int id)
        {
            ObtenerUsuarioActual();
            if(usuarioActual.idPersona != null)
            {
                NegocioEntity neg = nm.GetNegocioById(id);
                Persona p = pm.GetPersonaById((int)usuarioActual.idPersona);

                ViewBag.idTipoLugarHospedaje = neg.LugarHospedaje.FirstOrDefault().idTipoLugarHospedaje;
                ViewBag.idNegocio = neg.idNegocio;
                ViewBag.Persona = p;

                return View();
            }
            else
            {
                return RedirectToAction("DatosPersonales", "Persona", new { returnUrl = "../Reservas/SolicitarReserva/" + id });
            }
        }
        [HttpPost]
        public ActionResult SolicitarReserva(SolicitudEntity solicitud, string fechaDesde, string fechaHasta, int idNegocio)
        {
            ObtenerUsuarioActual();
            solicitud.fechaDesde = Convert.ToDateTime(fechaDesde);
            solicitud.fechaHasta = Convert.ToDateTime(fechaHasta);
            solicitud.idNegocio = idNegocio;
            solicitud.idUsuarioSolicitante = usuarioActual.idUsuario;

            rm.AddSolicitudReserva(solicitud);

            return RedirectToAction("IndexHospedajes", "Negocios");
        }
        public ActionResult SolicitudesReserva(int idNegocio)
        {
            List<SolicitudEntity> solicitudes = rm.GetSolicitudesReserva(idNegocio);
            ViewBag.idNegocio = idNegocio;

            return View(solicitudes);
        }
        public ActionResult VerSolicitudReserva(int idSolicitud)
        {
            SolicitudEntity sol = rm.GetSolicitudReservaById(idSolicitud);
            Persona p = pm.GetPersonaById((int)sol.Usuarios.idPersona);
            NegocioEntity neg = nm.GetNegocioById((int)sol.idNegocio);

            ViewBag.Persona = p;
            ViewBag.idTipoLugarHospedaje = neg.LugarHospedaje.FirstOrDefault().idTipoLugarHospedaje;

            return View(sol);
        }
        public ActionResult TusHabitaciones(int idLugarHospedaje)
        {
            int idHotel = int.Parse(db.Hotel.Where(h => h.idLugarHospedaje == idLugarHospedaje).Select(h => h.idHotel).FirstOrDefault().ToString());
            return RedirectToAction("Index", "Habitaciones", new { idHotel = idHotel });
        }
        public ActionResult TusDptosOCabanas(int idLugarHospedaje)
        {
            int idComplejo = int.Parse(db.Complejo.Where(c => c.idLugarHospedaje == idLugarHospedaje).Select(c => c.idComplejo).FirstOrDefault().ToString());
            return RedirectToAction("Index", "DptoOCabana", new { idComplejo = idComplejo });
        }
        public bool ValidarPermisoVista(string controlador, string vista) //METODO ÚNICO DEL CONTROLADOR PARA VALIDAR PERMISO DE LA VISTA (LLAMA AL MANEJADOR).
        {
            ObtenerUsuarioActual();
            return um.ValidarPermisoVista(usuarioActual, controlador, vista);
        }
        public void ObtenerUsuarioActual()
        {
            usuarioActual = (UsuarioEntity)Session["User"];
        }
	}
}

V 1.1/ProyectoFinal/ProyectoFinal/Views/Reservas/GestionReservas.cshtml
@model BussinesEntities.NegocioEntity

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Evaluar Modulo Reserva</title>
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/assets/plugins/animate.css/animate.min.css">
    <!-- end: MAIN CSS -->
    <!-- start: CSS REQUIRED FOR SUBVIEW CONTENTS -->
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="~/assets/plugins/summernote/dist/summernote.css">
    <link rel="stylesheet" href="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="~/assets/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-select/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
    <link rel="stylesheet" href="~/assets/plugins/DataTables/media/css/DT_bootstrap.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
    <!-- end: CSS REQUIRED FOR THIS SUBVIEW CONTENTS-->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CORE CSS -->
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="stylesheet" href="~/assets/css/styles-responsive.css">
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <link rel="stylesheet" href="~/assets/css/themes/theme-default.css" type="text/css" id="skin_color">
    <link rel="stylesheet" href="~/assets/css/print.css" type="text/css" media="print" />
    <!-- end: CORE CSS -->
</head>
<body>
    <div class="panel panel-white">
        <div class="panel-heading">
            <h4 class="panel-title pull-right">Gestión<span class="text-bold"> de Reservas</span></h4>
        </div>
        <div class="panel-body">
            <br />
            <h2>Gestion de Reservas - @Model.nombre</h2>
            <br />
           
                        @{
                            if (Model.LugarHospedaje.FirstOrDefault().idTipoLugarHospedaje == 2)
                            {<br />
                            <button class="btn btn-green btn-lg btn-block" id="btnTusDptosOCabana" onclick="window.location = '@Url.Action("TusDptosOCabanas", "Reservas", new { idLugarHospedaje = Model.LugarHospedaje.FirstOrDefault().idLugarHospedaje })'">
                                TUS DPTOS Ó CABAÑAS
                            </button><br />
                            }
                            else
                            {<br />
                            <button class="btn btn-green btn-lg btn-block" id="btnTusHabitaciones" onclick="window.location = '@Url.Action("TusHabitaciones","Reservas", new { idLugarHospedaje = Model.LugarHospedaje.FirstOrDefault().idLugarHospedaje })'">
                                TUS HABITACIONES
                            </button><br />
                            }
                        }
                   

                        <button class="btn btn-green btn-lg btn-block" id="btnSolicitudes" onclick="window.location = '@Url.Action("SolicitudesReserva", "Reservas", new { idNegocio = Model.idNegocio })'">
                            SOLICITUDES
                        </button><br />


                
        </div>
    </div>
          
            <script src="~/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
            <!--<![endif]-->
            <script src="~/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
            <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
            <script src="~/assets/plugins/blockUI/jquery.blockUI.js"></script>
            <script src="~/assets/plugins/iCheck/jquery.icheck.min.js"></script>
            <script src="~/assets/plugins/moment/min/moment.min.js"></script>
            <script src="~/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
            <script src="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
            <script src="~/assets/plugins/bootbox/bootbox.min.js"></script>
            <script src="~/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
            <script src="~/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
            <script src="~/assets/plugins/jquery.appear/jquery.appear.js"></script>
            <script src="~/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
            <script src="~/assets/plugins/velocity/jquery.velocity.min.js"></script>
            <script src="~/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
            <!-- end: MAIN JAVASCRIPTS -->
            <!-- start: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
            <script src="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
            <script src="~/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
            <script src="~/assets/plugins/toastr/toastr.js"></script>
            <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
            <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
            <script src="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
            <script src="~/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
            <script src="~/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
            <script src="~/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
            <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
            <script src="~/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
            <script src="~/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
            <script src="~/assets/plugins/truncate/jquery.truncate.js"></script>
            <script src="~/assets/plugins/summernote/dist/summernote.min.js"></script>
            <script src="~/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
            <script src="~/assets/js/subview.js"></script>
            <script src="~/assets/js/subview-examples.js"></script>
            <!-- end: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
            <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
            <script src="~/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
            <script src="~/assets/plugins/autosize/jquery.autosize.min.js"></script>
            <script src="~/assets/plugins/select2/select2.min.js"></script>
            <script src="~/assets/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
            <script src="~/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
            <script src="~/assets/plugins/jquery-maskmoney/jquery.maskMoney.js"></script>
            <script src="~/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
            <script src="~/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpicker/js/commits.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js"></script>
            <script src="~/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
            <script src="~/assets/plugins/jQuery-Tags-Input/jquery.tagsinput.js"></script>
            <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
            <script src="~/assets/plugins/ckeditor/ckeditor.js"></script>
            <script src="~/assets/plugins/ckeditor/adapters/jquery.js"></script>
            <script src="~/assets/js/form-elements.js"></script>
            <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
            <!-- start: CORE JAVASCRIPTS  -->
            <script src="~/assets/js/main.js"></script>
            <!-- end: CORE JAVASCRIPTS  -->
            <script>
                jQuery(document).ready(function () {
                    Main.init();

                    FormElements.init();
                    SVExamples.init();
                });
            </script>
</body>
</html>

V 1.1/ProyectoFinal/ProyectoFinal/Views/Reservas/SolicitudesReserva.cshtml
@model IEnumerable<BussinesEntities.SolicitudEntity>
@using GridMvc.Html

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Solicitudes Reservas</title>
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/assets/plugins/animate.css/animate.min.css">
    <!-- end: MAIN CSS -->
    <!-- start: CSS REQUIRED FOR SUBVIEW CONTENTS -->
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="~/assets/plugins/summernote/dist/summernote.css">
    <link rel="stylesheet" href="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="~/assets/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-select/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
    <link rel="stylesheet" href="~/assets/plugins/DataTables/media/css/DT_bootstrap.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
    <!-- end: CSS REQUIRED FOR THIS SUBVIEW CONTENTS-->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CORE CSS -->
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="stylesheet" href="~/assets/css/styles-responsive.css">
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <link rel="stylesheet" href="~/assets/css/themes/theme-default.css" type="text/css" id="skin_color">
    <link rel="stylesheet" href="~/assets/css/print.css" type="text/css" media="print" />
    <!-- end: CORE CSS -->

    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.custom.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>

    <script type="text/javascript">

        var perfil = "@ViewBag.Perfil"     
        var mensaje = "@ViewBag.Mensaje"

        $(document).ready(function(){
        });
          </script>

</head>
<body>

    <div class="panel panel-white">
        <div class="panel-heading">
            <h4 class="panel-title pull-right">Evaluar Modulo <span class="text-bold">Gestión de Reservas</span></h4>
        </div>
        <div class="panel-body">
            SOLICITUDES DE RESERVA
            <br />
            <br />
            @if (Model.Count() != 0)
            {
                @helper botonVer(BussinesEntities.SolicitudEntity s)
{
                <button id="btnVerSolicitud" onclick="window.location = '@Url.Action("VerSolicitudReserva", "Reservas", new { idSolicitud = s.idSolicitud })'" style="font-size:10px">VER</button>
}

                @Html.Grid(Model).Columns(columns =>
        {
            //columns.Add(model => model.fechaAlta).Titled("Fecha Alta");
            columns.Add(model => model.Usuarios.nombreUsuario).Titled("Usuario").SetWidth(50);
            columns.Add(model => model.fechaDesde).Titled("Fecha Desde").SetWidth(50);
            columns.Add(model => model.fechaHasta).Titled("Fecha Hasta").SetWidth(50);
            columns.Add(model => model.cantidadPersonas).Titled("Cant. Personas").SetWidth(50);
            columns.Add(model => model.idSolicitud)
                .Titled("Acción")
                .Encoded(false)
                .Sanitized(false)
                .SetWidth(100)
                .RenderValueAs(s => botonVer(s));
        }).WithPaging(10).Sortable(true)
            }
            else
            {

                <div id="NoSolicitudes" style="align-self:center; font-size:20px; display:none">
                    <strong>
                        No tenés Solicitudes Recibidas.
                    </strong>
                </div>

            }
            <br />
        </div>
    </div>
           
            @Html.ActionLink("VOLVER", "GestionReservas", new { idNegocio = ViewBag.idNegocio })
            <script src="~/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
            <!--<![endif]-->
            <script src="~/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
            <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
            <script src="~/assets/plugins/blockUI/jquery.blockUI.js"></script>
            <script src="~/assets/plugins/iCheck/jquery.icheck.min.js"></script>
            <script src="~/assets/plugins/moment/min/moment.min.js"></script>
            <script src="~/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
            <script src="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
            <script src="~/assets/plugins/bootbox/bootbox.min.js"></script>
            <script src="~/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
            <script src="~/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
            <script src="~/assets/plugins/jquery.appear/jquery.appear.js"></script>
            <script src="~/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
            <script src="~/assets/plugins/velocity/jquery.velocity.min.js"></script>
            <script src="~/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
            <!-- end: MAIN JAVASCRIPTS -->
            <!-- start: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
            <script src="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
            <script src="~/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
            <script src="~/assets/plugins/toastr/toastr.js"></script>
            <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
            <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
            <script src="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
            <script src="~/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
            <script src="~/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
            <script src="~/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
            <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
            <script src="~/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
            <script src="~/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
            <script src="~/assets/plugins/truncate/jquery.truncate.js"></script>
            <script src="~/assets/plugins/summernote/dist/summernote.min.js"></script>
            <script src="~/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
            <script src="~/assets/js/subview.js"></script>
            <script src="~/assets/js/subview-examples.js"></script>
            <!-- end: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
            <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
            <script src="~/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
            <script src="~/assets/plugins/autosize/jquery.autosize.min.js"></script>
            <script src="~/assets/plugins/select2/select2.min.js"></script>
            <script src="~/assets/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
            <script src="~/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
            <script src="~/assets/plugins/jquery-maskmoney/jquery.maskMoney.js"></script>
            <script src="~/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
            <script src="~/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpicker/js/commits.js"></script>
            <script src="~/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js"></script>
            <script src="~/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
            <script src="~/assets/plugins/jQuery-Tags-Input/jquery.tagsinput.js"></script>
            <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
            <script src="~/assets/plugins/ckeditor/ckeditor.js"></script>
            <script src="~/assets/plugins/ckeditor/adapters/jquery.js"></script>
            <script src="~/assets/js/form-elements.js"></script>
            <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
            <!-- start: CORE JAVASCRIPTS  -->
            <script src="~/assets/js/main.js"></script>
            <!-- end: CORE JAVASCRIPTS  -->
            <script>
                jQuery(document).ready(function () {
                    Main.init();

                    FormElements.init();
                    SVExamples.init();
                });
            </script>
</body>

</html>